name: Build

on: push

jobs:
  # call_reusable_workflow:
  #   uses: ./.github/workflows/reusable-workflow.yml

  build:
    runs-on: ubuntu-latest
    steps:
      # see https://github.com/actions/checkout
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        uses: ./.github/actions/install-dependencies

      - name: Build application
        run: |
          pnpm run build
