name: Build

on:
  # see https://docs.github.com/en/actions/using-workflows/reusing-workflows
  workflow_call:
    inputs:
      artifact-name:
        type: string
        default: artifact
      build-command:
        type: string
        default: pnpm run build
      environment:
        type: string
        required: true
      environment-url:
        type: string
        required: true
      publish-directory:
        type: string
        default: dist

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}
    steps:
      # see https://github.com/actions/checkout
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        uses: ./.github/actions/install-dependencies

      - name: Build application
        run: ${{ inputs.build-command }}

      # see https://github.com/actions/upload-artifact
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.artifact-name }}
          path: ${{ inputs.publish-directory }}

      - name: Print DEPLOY_ENV
        run: |
          echo "${{ vars.DEPLOY_ENV }}"

  list:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: ${{ inputs.environment }}
      url: ${{ inputs.environment-url }}
    steps:
      # see https://github.com/actions/download-artifact
      - name: Download artifact
        id: download
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact-name }}
          path: ${{ inputs.publish-directory }}

      - name: Display structure of downloaded files
        working-directory: ${{ inputs.publish-directory }}
        run: ls -R

      - name: Print download path
        run: echo ${{steps.download.outputs.download-path}}

      - name: Print DEPLOY_ENV
        run: |
          echo "${{ vars.DEPLOY_ENV }}"
