name: Build

on:
  # see https://docs.github.com/en/actions/using-workflows/reusing-workflows
  workflow_call:
    inputs:
      build-command:
        # required: true
        type: string
        default: pnpm run build

      publish-directory:
        # required: true
        type: string
        default: dist

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # see https://github.com/actions/checkout
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        uses: ./.github/actions/install-dependencies

      - name: Build application
        run: ${{ inputs.build-command }}

      # see https://github.com/actions/upload-artifact
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          path: ${{ inputs.publish-directory }}

  list:
    runs-on: ubuntu-latest
    needs: build
    steps:
      # see https://github.com/actions/download-artifact
      - name: Download artifact
        id: download
        uses: actions/download-artifact@v3
        with:
          path: ${{ inputs.publish-directory }}

      - name: Display structure of downloaded files
        working-directory: ${{ inputs.publish-directory }}
        run: ls -R

      - name: Print download path
        run: echo ${{steps.download.outputs.download-path}}
