name: Build (parallel jobs)

on: push

jobs:
  default:
    uses: ./.github/workflows/reusable-workflow.yml

  change-output-directory:
    uses: ./.github/workflows/reusable-workflow.yml
    with:
      build-command: pnpm run build --outDir output
      publish-directory: output
