name: Environment

on: workflow_dispatch

jobs:
  production:
    runs-on: ubuntu-latest
    if: github.ref_name == 'main'
    environment:
      name: production
      url: "${{ vars.ENVIRONMENT_URL }}"
    steps:
      - name: Print var
        run: |
          echo "${{ vars.DEPLOY_ENV }}"
          echo $DEPLOY_ENV
          echo $ENVIRONMENT_URL
          echo $TEST_REPOSITORY_VARIABLE

  development:
    runs-on: ubuntu-latest
    if: github.ref_name == 'develop'
    environment:
      name: development
      url: "${{ vars.ENVIRONMENT_URL }}"
    steps:
      - name: Print var
        run: |
          echo "${{ vars.DEPLOY_ENV }}"
          echo $DEPLOY_ENV
          echo $ENVIRONMENT_URL
          echo $TEST_REPOSITORY_VARIABLE

  post-job:
    runs-on: ubuntu-latest
    if: always() && contains(needs.*.result, 'success')
    needs:
      - production
      - development
    steps:
      - name: Print var
        run: |
          echo "${{ vars.DEPLOY_ENV }}"
          echo $DEPLOY_ENV
          echo $ENVIRONMENT_URL
          echo $TEST_REPOSITORY_VARIABLE

  empty-url:
    runs-on: ubuntu-latest
    if: github.ref_name == 'main'
    environment:
      name: production
      url: ""
    steps:
      - name: Print var
        run: |
          echo "${{ vars.DEPLOY_ENV }}"
          echo $DEPLOY_ENV
          echo $ENVIRONMENT_URL
          echo $TEST_REPOSITORY_VARIABLE
