name: Environment

on: workflow_dispatch

jobs:
  production:
    runs-on: ubuntu-latest
    if: github.ref_name == 'main'
    environment:
      name: production
      url: "${{ vars.ENVIRONMENT_URL }}"
    steps:
      - name: Print var
        run: |
          echo "${{ vars.DEPLOY_ENV }}"

  development:
    runs-on: ubuntu-latest
    if: github.ref_name == 'develop'
    environment:
      name: development
      url: "${{ vars.ENVIRONMENT_URL }}"
    steps:
      - name: Print var
        run: |
          echo "${{ vars.DEPLOY_ENV }}"

  post-job:
    runs-on: ubuntu-latest
    if: always() && contains(needs.*.result, 'success')
    needs:
      - production
      - development
    steps:
      - name: Print var
        run: |
          echo "${{ vars.DEPLOY_ENV }}"

  empty-url:
    runs-on: ubuntu-latest
    if: github.ref_name == 'main'
    environment:
      name: production
      url: ""
    steps:
      - name: Print var
        run: |
          echo "${{ vars.DEPLOY_ENV }}"
