name: matrix

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  basic:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    strategy:
      matrix:
        targets: ["a", "b", "c"]
    steps:
      - run: |
          echo "${{ matrix.targets }}"
