name: matrix

on:
  push:
    branches:
      - main

jobs:
  basic:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    strategy:
      matrix:
        targets: ["a", "b", "c"]
    steps:
      - run: |
          echo "${{ matrix.targets }}"

  exclude:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    strategy:
      matrix:
        targets: ["a", "b", "c"]
        exclude:
          - targets: "a"
          - targets: "b"
          - targets: "c"
    steps:
      - run: |
          echo "${{ matrix.targets }}"

  include:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    strategy:
      matrix:
        include:
          - targets: "a"
    steps:
      - run: |
          echo "${{ matrix.targets }}"

  changes:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    outputs:
      a: ${{ steps.filter.outputs.a }}
      b: ${{ steps.filter.outputs.b }}
      changes: ${{ steps.filter.outputs.changes }}
    steps:
      # see https://github.com/actions/checkout
      - name: Checkout
        uses: actions/checkout@v4

      # see https://github.com/dorny/paths-filter
      - name: Change detection
        uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            a:
              - 'apps/a/**'
            b:
              - 'apps/b/**'
      - run: |
          echo "${{ toJSON(steps.filter.outputs) }}"
      - run: |
          echo "${{ join(steps.filter.outputs.changes) }}"
      - run: |
          '${{ join(steps.filter.outputs.changes) }}' | jq 'length'

  # check:
  #   runs-on: ubuntu-latest
  #   timeout-minutes: 3
  #   needs: changes
  #   if: join(needs.changes.outputs.changes) != '[]'
  #   steps:
  #     - run: |
  #         echo "${{ toJSON(needs.changes.outputs.changes) }}"

  dynamic:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    needs:
      - changes
      # - check
    if: join(needs.changes.outputs.changes) != '[]'
    strategy:
      matrix:
        changes: ${{ fromJSON(needs.changes.outputs.changes) }}
    steps:
      - run: |
          echo "${{ matrix.changes }}"
