# see https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-output-parameter
name: output

on: workflow_dispatch

jobs:
  save:
    runs-on: ubuntu-latest

    # https://zenn.dev/kenpi/articles/af6fb5b4c2675e
    environment:
      name: production
      url: https://github.com/etm7fp/try-env/tree/main

    # see https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-output-parameter
    outputs:
      message: ${{ steps.save_step.outputs.message }}
      secret_message: ${{ steps.save_step.outputs.secret_message }}
      variable_message: ${{ steps.save_step.outputs.variable_message }}
    steps:
      - name: Save message
        id: save_step
        run: |
          echo "message=hello" >> $GITHUB_OUTPUT
          secret_message=${{ secrets.SECRET_MESSAGE }}
          echo "::add-mask::$secret_message"
          echo "secret_message=$secret_message" >> $GITHUB_OUTPUT
          echo "variable_message=${{ vars.VARIABLE_MESSAGE }}" >> $GITHUB_OUTPUT
  print:
    runs-on: ubuntu-latest
    needs: save
    steps:
      - name: Print message
        run: |
          echo "${{ needs.save.outputs.message }}"
          echo "${{ secrets.SECRET_MESSAGE }}"
          echo "${{ needs.save.outputs.secret_message }}"
          echo "${{ needs.save.outputs.variable_message }}"
