name: output

on: push

jobs:
  save:
    runs-on: ubuntu-latest
    steps:
      - name: Save message
        run: |
          echo "message=hello" >> $GITHUB_OUTPUT
  print:
    runs-on: ubuntu-latest
    needs: save
    steps:
      - name: Print message
        run: |
          echo "${{ needs.save.outputs }}"
