name: paths-filter

on:
  push:
    branches:
      - main
    paths:
      - "apps/a/**"
      - "apps/b/**"
      - "!**.md"

jobs:
  filter:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - run: cat $GITHUB_EVENT_PATH
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            a:
              - 'apps/a/**'
            b:
              - 'apps/b/**'
            configs:
              - 'packages/configs/**'
      - run: |
          echo "${{ toJSON(steps.changes.outputs) }}"
      - if: steps.changes.outputs.a == 'true'
        run: |
          echo a
