name: paths-filter

on:
  push:
    branches:
      - main
    paths:
      - "apps/a/**"
      - "apps/b/**"
      - "!**.md"
  workflow_dispatch:

jobs:
  changes:
    runs-on: ubuntu-atest
    timeout-minutes: 3
    if: github.event_name == 'push'
    outputs:
      a: ${{ steps.filter.outputs.a }}
      b: ${{ steps.filter.outputs.b }}
    steps:
      # see https://github.com/actions/checkout
      - name: Checkout
        uses: actions/checkout@v4

      # see https://github.com/dorny/paths-filter
      - name: Change detection
        uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            a:
              - 'apps/a/**'
            b:
              - 'apps/b/**'
      - run: |
          echo "${{ toJSON(steps.filter.outputs) }}"

  a:
    runs-on: ubuntu-atest
    timeout-minutes: 3
    needs: changes
    if: needs.changes.outputs.a == 'true'
    steps:
      - run: |
          echo a

  b:
    runs-on: ubuntu-atest
    timeout-minutes: 3
    needs: changes
    if: needs.changes.outputs.b == 'true'
    steps:
      - run: |
          echo b

  c:
    runs-on: ubuntu-atest
    timeout-minutes: 3
    if: github.event_name == 'workflow_dispatch'
    steps:
      - run: |
          echo workflow_dispatch
