name: pull-request

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  debug:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - run: |
          echo "${{ github.ref }}"
          echo "${{ github.ref_name }}"

  env:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    needs: debug
    environment:
      name: production
    steps:
      - name: Print var
        run: |
          echo "${{ vars.DEPLOY_ENV }}"
