name: Reusable workflow

on: workflow_call

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      # see https://github.com/actions/checkout
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        uses: ./.github/actions/install-dependencies
